services:
  receiver:
    build:
      context: .
      dockerfile: apps/receiver/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/receiver/.env
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    env_file:
      - apps/worker/.env
    restart: unless-stopped
